#!/bin/bash
# echo "date '+%b %d %Y %a %H:%M:%S ] "
#. /home/drishal/dotfiles/suckless/dwmblocks/scripts/themes/onedark.sh
 printf "[$(date '+%b %d %Y (%a) %H:%M:%S')]"
# printf "$(date '+%b %d %Y (%a) %H:%M:%S "
